name: Publish Package

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release type"
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"
          registry-url: "@gohanfromgoku:registry=https://registry.npmjs.org/"

      - name: Bump version
        run: |
          npm i -g yarn
          yarn version --${{ github.event.inputs.releaseType }}

      - name: Push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git push origin HEAD

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_TOKEN }}
        run: npm publish --access public --no-git-tag-version
